export const COUNTRIES = [
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'Pakistan',
  'India',
  'United Arab Emirates',
  'Saudi Arabia',
  'Germany',
  'France',
  'Spain',
  'Italy',
  'Netherlands',
  'Sweden',
  'Singapore',
  'Japan',
  'South Korea',
  'Philippines',
  'Indonesia',
  'Brazil',
  'Mexico',
  'South Africa',
  'Nigeria',
  'Egypt',
  'Turkey',
] as const;
